server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: classpath:/files/uploads
