server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100KB
      max-file-size: 200MB
      max-request-size: 215MB

file:
  upload-dir: D:\\GFM\\Projects\\fileserver\\uploads

fabric:
  createFile: http://ec2-54-156-158-129.compute-1.amazonaws.com:8080/fabric-transactions/create-file/
  shareFile: http://ec2-54-156-158-129.compute-1.amazonaws.com:8080/fabric-transactions/share-file/
  revokeFileAccess: http://ec2-54-156-158-129.compute-1.amazonaws.com:8080/fabric-transactions/revoke-file-access/
